In [223]:
import pandas as pd
import numpy as np
import os
import re

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)
pd.set_option('display.width', 2000)
pd.set_option('display.expand_frame_repr', False)
pd.set_option("display.max_colwidth", None)  # or a large number like 2000

In [224]:
print(os.getcwd())

/run/media/christianm/nvme_storage/Projects/Repos/kaggle_sms_spam_collection/notebooks

In [225]:
df = pd.read_csv("../data/raw/spam.csv", encoding="latin1")

In [226]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   str
 1   v2          5572 non-null   str
 2   Unnamed: 2  50 non-null     str
 3   Unnamed: 3  12 non-null     str
 4   Unnamed: 4  6 non-null      str
dtypes: str(5)
memory usage: 217.8 KB

In [227]:
df.head()

     v1                                                                                                                                                           v2 Unnamed: 2 Unnamed: 3 Unnamed: 4
0   ham                                              Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...        NaN        NaN        NaN
1   ham                                                                                                                                Ok lar... Joking wif u oni...        NaN        NaN        NaN
2  spam  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's        NaN        NaN        NaN
3   ham                                                                                                            U dun say so early hor... U c already then say...        NaN        NaN        NaN
4   ham                                                                                                Nah I don't think he goes to usf, he lives around here though        NaN        NaN        NaN

In [228]:
df[df["Unnamed: 4"].notna()]

       v1                                                                                                                                               v2                                                                    Unnamed: 2                                Unnamed: 3                                                Unnamed: 4
281   ham                                                                                                                              \Wen u miss someone   the person is definitely special for u..... But if the person is so special                          why to miss them                             just Keep-in-touch\" gdeve.."
1038  ham  Edison has rightly said, \A fool can ask more questions than a wise man can answer\" Now you know why all of us are speechless during ViVa.. GM                                                                            GN                                        GE                                                   GNT:-)"
2255  ham                                                                                                    I just lov this line: \Hurt me with the truth                                                                  I don't mind  i wil tolerat.bcs ur my someone..... But   Never comfort me with a lie\" gud ni8 and sweet dreams"
3525  ham                                                     \HEY BABE! FAR 2 SPUN-OUT 2 SPK AT DA MO... DEAD 2 DA WRLD. BEEN SLEEPING ON DA SOFA ALL DAY                                                              HAD A COOL NYTHO                            TX 4 FONIN HON                       CALL 2MWEN IM BK FRMCLOUD 9! J X\""
4668  ham                                                                           When I was born, GOD said, \Oh No! Another IDIOT\". When you were born                                                                      GOD said          \"OH No! COMPETITION\". Who knew           one day these two will become FREINDS FOREVER!"
5048  ham  Edison has rightly said, \A fool can ask more questions than a wise man can answer\" Now you know why all of us are speechless during ViVa.. GM                                                                            GN                                        GE                                                   GNT:-)"

In [229]:
df["Unnamed: 4"][281]

' just Keep-in-touch\\" gdeve.."'

# Data Cleaning
## Replacing NA with empty string - then concat the strings to one

In [230]:
df.fillna("", inplace=True)

        v1                                                                                                                                                                 v2 Unnamed: 2 Unnamed: 3 Unnamed: 4
0      ham                                                    Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...
1      ham                                                                                                                                      Ok lar... Joking wif u oni...
2     spam        Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
3      ham                                                                                                                  U dun say so early hor... U c already then say...
4      ham                                                                                                      Nah I don't think he goes to usf, he lives around here though
...    ...                                                                                                                                                                ...        ...        ...        ...
5567  spam  This is the 2nd time we have tried 2 contact u. U have won the å£750 Pound prize. 2 claim is easy, call 087187272008 NOW1! Only 10p per minute. BT-national-rate.
5568   ham                                                                                                                              Will Ì_ b going to esplanade fr home?
5569   ham                                                                                                          Pity, * was in mood for that. So...any other suggestions?
5570   ham                                      The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free
5571   ham                                                                                                                                         Rofl. Its true to its name

[5572 rows x 5 columns]

In [231]:

df["text"] = (
    df[["v2", "Unnamed: 2", "Unnamed: 3", "Unnamed: 4"]]
      .fillna("")                 # avoid "nan" strings
      .astype(str)
      .agg(" ".join, axis=1)
)

In [232]:
df.head()

     v1                                                                                                                                                           v2 Unnamed: 2 Unnamed: 3 Unnamed: 4                                                                                                                                                            text
0   ham                                              Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...                                                                               Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...
1   ham                                                                                                                                Ok lar... Joking wif u oni...                                                                                                                                                                 Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's                                   Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
3   ham                                                                                                            U dun say so early hor... U c already then say...                                                                                                                                             U dun say so early hor... U c already then say...
4   ham                                                                                                Nah I don't think he goes to usf, he lives around here though                                                                                                                                 Nah I don't think he goes to usf, he lives around here though

In [233]:
df["target"] = df["v1"]
df.drop(columns=["v1", "v2", "Unnamed: 2", "Unnamed: 3", "Unnamed: 4"], inplace=True)

In [234]:
df.head()

                                                                                                                                                             text target
0                                              Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...       ham
1                                                                                                                                Ok lar... Joking wif u oni...       ham
2  Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's      spam
3                                                                                                            U dun say so early hor... U c already then say...       ham
4                                                                                                Nah I don't think he goes to usf, he lives around here though       ham

In [235]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    5572 non-null   str
 1   target  5572 non-null   str
dtypes: str(2)
memory usage: 87.2 KB

In [236]:
df["target"].value_counts()

target
ham     4825
spam     747
Name: count, dtype: int64

In [237]:
for i in range(0, 100):
    print(i, df["target"][i], df["text"][i])

0 ham Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...
1 ham Ok lar... Joking wif u oni...
2 spam Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
3 ham U dun say so early hor... U c already then say...
4 ham Nah I don't think he goes to usf, he lives around here though
5 spam FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv
6 ham Even my brother is not like to speak with me. They treat me like aids patent.
7 ham As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune
8 spam WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.
9 spam Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030
10 ham I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.
11 spam SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info
12 spam URGENT! You have won a 1 week FREE membership in our å£100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18
13 ham I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.
14 ham I HAVE A DATE ON SUNDAY WITH WILL!!
15 spam XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL
16 ham Oh k...i'm watching here:)
17 ham Eh u remember how 2 spell his name... Yes i did. He v naughty make until i v wet.
18 ham Fine if thatåÕs the way u feel. ThatåÕs the way its gota b
19 spam England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/Ì¼1.20 POBOXox36504W45WQ 16+
20 ham Is that seriously how you spell his name?
21 ham IÛ÷m going to try for 2 months ha ha only joking
22 ham So Ì_ pay first lar... Then when is da stock comin...
23 ham Aft i finish my lunch then i go str down lor. Ard 3 smth lor. U finish ur lunch already?
24 ham Ffffffffff. Alright no way I can meet up with you sooner?
25 ham Just forced myself to eat a slice. I'm really not hungry tho. This sucks. Mark is getting worried. He knows I'm sick when I turn down pizza. Lol
26 ham Lol your always so convincing.
27 ham Did you catch the bus ? Are you frying an egg ? Did you make a tea? Are you eating your mom's left over dinner ? Do you feel my Love ?
28 ham I'm back &amp; we're packing the car now, I'll let you know if there's room
29 ham Ahhh. Work. I vaguely remember that! What does it feel like? Lol
30 ham Wait that's still not all that clear, were you not sure about me being sarcastic or that that's why x doesn't want to live with us
31 ham Yeah he got in at 2 and was v apologetic. n had fallen out and she was actin like spoilt child and he got caught up in that. Till 2! But we won't go there! Not doing too badly cheers. You?
32 ham K tell me anything about you.
33 ham For fear of fainting with the of all that housework you just did? Quick have a cuppa
34 spam Thanks for your subscription to Ringtone UK your mobile will be charged å£5/month Please confirm by replying YES or NO. If you reply NO you will not be charged
35 ham Yup... Ok i go home look at the timings then i msg Ì_ again... Xuhui going to learn on 2nd may too but her lesson is at 8am
36 ham Oops, I'll let you know when my roommate's done
37 ham I see the letter B on my car
38 ham Anything lor... U decide...
39 ham Hello! How's you and how did saturday go? I was just texting to see if you'd decided to do anything tomo. Not that i'm trying to invite myself or anything!
40 ham Pls go ahead with watts. I just wanted to be sure. Do have a great weekend. Abiola
41 ham Did I forget to tell you ? I want you , I need you, I crave you ... But most of all ... I love you my sweet Arabian steed ... Mmmmmm ... Yummy
42 spam 07732584351 - Rodger Burns - MSG = We tried to call you re your reply to our sms for a free nokia mobile + free camcorder. Please call now 08000930705 for delivery tomorrow
43 ham WHO ARE YOU SEEING?
44 ham Great! I hope you like your man well endowed. I am  &lt;#&gt;  inches...
45 ham No calls..messages..missed calls
46 ham Didn't you get hep b immunisation in nigeria.
47 ham Fair enough, anything going on?
48 ham Yeah hopefully, if tyler can't do it I could maybe ask around a bit
49 ham U don't know how stubborn I am. I didn't even want to go to the hospital. I kept telling Mark I'm not a weak sucker. Hospitals are for weak suckers.
50 ham What you thinked about me. First time you saw me in class.
51 ham A gram usually runs like  &lt;#&gt; , a half eighth is smarter though and gets you almost a whole second gram for  &lt;#&gt;
52 ham K fyi x has a ride early tomorrow morning but he's crashing at our place tonight
53 ham Wow. I never realized that you were so embarassed by your accomodations. I thought you liked it, since i was doing the best i could and you always seemed so happy about \the cave\". I'm sorry I didn't and don't have more to give. I'm sorry i offered. I'm sorry your room was so embarassing."
54 spam SMS. ac Sptv: The New Jersey Devils and the Detroit Red Wings play Ice Hockey. Correct or Incorrect? End? Reply END SPTV
55 ham Do you know what Mallika Sherawat did yesterday? Find out now @  &lt;URL&gt;
56 spam Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out!
57 ham Sorry, I'll call later in meeting.
58 ham Tell where you reached
59 ham Yes..gauti and sehwag out of odi series.
60 ham Your gonna have to pick up a $1 burger for yourself on your way home. I can't even move. Pain is killing me.
61 ham Ha ha ha good joke. Girls are situation seekers.
62 ham Its a part of checking IQ
63 ham Sorry my roommates took forever, it ok if I come by now?
64 ham Ok lar i double check wif da hair dresser already he said wun cut v short. He said will cut until i look nice.
65 spam As a valued customer, I am pleased to advise you that following recent review of your Mob No. you are awarded with a å£1500 Bonus Prize, call 09066364589
66 ham Today is \song dedicated day..\" Which song will u dedicate for me? Send this to all ur valuable frnds but first rply me..."
67 spam Urgent UR awarded a complimentary trip to EuroDisinc Trav, Aco&Entry41 Or å£1000. To claim txt DIS to 87121 18+6*å£1.50(moreFrmMob. ShrAcomOrSglSuplt)10, LS1 3AJ
68 spam Did you hear about the new \Divorce Barbie\"? It comes with all of Ken's stuff!"
69 ham I plane to give on this month end.
70 ham Wah lucky man... Then can save money... Hee...
71 ham Finished class where are you.
72 ham HI BABE IM AT HOME NOW WANNA DO SOMETHING? XX
73 ham K..k:)where are you?how did you performed?
74 ham U can call me now...
75 ham I am waiting machan. Call me once you free.
76 ham Thats cool. i am a gentleman and will treat you with dignity and respect.
77 ham I like you peoples very much:) but am very shy pa.
78 ham Does not operate after  &lt;#&gt;  or what
79 ham Its not the same here. Still looking for a job. How much do Ta's earn there.
80 ham Sorry, I'll call later
81 ham K. Did you call me just now ah?
82 ham Ok i am on the way to home hi hi
83 ham You will be in the place of that man
84 ham Yup next stop.
85 ham I call you later, don't have network. If urgnt, sms me.
86 ham For real when u getting on yo? I only need 2 more tickets and one more jacket and I'm done. I already used all my multis.
87 ham Yes I started to send requests to make it but pain came back so I'm back in bed. Double coins at the factory too. I gotta cash in all my nitros.
88 ham I'm really not up to it still tonight babe
89 ham Ela kano.,il download, come wen ur free..
90 ham Yeah do! DonÛ÷t stand to close tho- youÛ÷ll catch something!
91 ham Sorry to be a pain. Is it ok if we meet another night? I spent late afternoon in casualty and that means i haven't done any of y stuff42moro and that includes all my time sheets and that. Sorry.
92 ham Smile in Pleasure Smile in Pain Smile when trouble pours like Rain Smile when sum1 Hurts U Smile becoz SOMEONE still Loves to see u Smiling!!
93 spam Please call our customer service representative on 0800 169 6031 between 10am-9pm as you have WON a guaranteed å£1000 cash or å£5000 prize!
94 ham Havent planning to buy later. I check already lido only got 530 show in e afternoon. U finish work already?
95 spam Your free ringtone is waiting to be collected. Simply text the password \MIX\" to 85069 to verify. Get Usher and Britney. FML  PO Box 5249  MK17 92H. 450Ppw 16"
96 ham Watching telugu movie..wat abt u?
97 ham i see. When we finish we have loads of loans to pay
ham"   Hi. Wk been ok - on hols now! Yes on for a bit of a run. Forgot that i have hairdressers appointment at four so need to get home n shower beforehand. Does that cause prob for u?\"
99 ham Please don't text me anymore. I have nothing else to say.

In [238]:
assert len(df[df["text"].str.strip() == ""]) == 0

## Text Normalization

This then has to be done on the input data of new text as well!

A) normalize unicode / fix mojibake

B) Unescape HTML entities

C) Whitespace cleanup

D) placeholder strategy

In [239]:
df["text"][df["target"] == "spam"]

2             Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's
5                    FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv
8          WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.
9              Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030
11                               SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info
                                                                                        ...
5537                                                                           Want explicit SEX in 30 secs? Ring 02073162414 now! Costs 20p/min Gsex POBOX 2667 WC1N 3XX
5540     ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE MINS. INDIA CUST SERVs SED YES. L8ER GOT MEGA BILL. 3 DONT GIV A SHIT. BAILIFF DUE IN DAYS. I O å£250 3 WANT å£800
5547     Had your contract mobile 11 Mnths? Latest Motorola, Nokia etc. all FREE! Double Mins & Text on Orange tariffs. TEXT YES for callback, no to remove from records.
5566                  REMINDER FROM O2: To get 2.50 pounds free call credit and details of great offers pls reply 2 this text with your valid name, house no and postcode
5567    This is the 2nd time we have tried 2 contact u. U have won the å£750 Pound prize. 2 claim is easy, call 087187272008 NOW1! Only 10p per minute. BT-national-rate.
Name: text, Length: 747, dtype: str

In [252]:
import re
import html
import unicodedata

# ---------- patterns ----------
URL_RE = re.compile(r"(?:https?://\S+|www\.\S+|http://\S+)", flags=re.IGNORECASE)
MONEY_RE = re.compile(r"[£$€]\s*\d{1,3}(?:,\d{3})*(?:\.\d+)?|[£$€]\s*\d+(?:\.\d+)?")
PHONE_RE = re.compile(r"(?<!\w)\d(?:[\s-]?\d){6,}(?!\w)")  # 7+ digits with optional spaces/dashes

# strict number token:
# - 12
# - 1,200
# - 12.5
# - 1,200.50
# avoids weird partials like "1⁄4" fragments
NUM_RE = re.compile(r"\b(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?\b")

# common mojibake traces observed in this dataset
MOJIBAKE_RE = re.compile(r"(?:å£|â£|Ì¼|�|Ã|Â)")


def normalize_text_safe(text: str) -> str:
    if text is None:
        return ""
    text = str(text)

    # 1) targeted replacements FIRST (before NFKC can mutate sequences)
    text = text.replace("å£", "£").replace("â£", "£").replace("Ì¼", "£")

    # 2) html + unicode normalize
    text = html.unescape(text)
    text = unicodedata.normalize("NFKC", text)

    # 3) non-breaking spaces
    text = text.replace("\u00A0", " ")
    return text


def split_alnum_boundaries(text: str) -> str:
    if text is None:
        return ""
    # POBOXox36504W45WQ -> POBOXox 36504 W 45 WQ
    text = re.sub(r"(?<=[A-Za-z])(?=\d)", " ", text)
    text = re.sub(r"(?<=\d)(?=[A-Za-z])", " ", text)
    return text


def apply_placeholders_v2(text: str) -> str:
    if text is None:
        return ""

    # order matters
    text = URL_RE.sub(" <URL> ", text)
    text = MONEY_RE.sub(" <MONEY> ", text)
    text = PHONE_RE.sub(" <PHONE> ", text)

    # shield unicode fractions before number replacement
    text = re.sub(r"\d+\s*[⁄/]\s*\d+", " <FRACTION> ", text)  # optional token

    # then general numbers
    text = NUM_RE.sub(" <NUM> ", text)
    return text


def clean_whitespace(text: str) -> str:
    return re.sub(r"\s+", " ", text or "").strip()


def preprocess_sms_v2(text: str, use_placeholders: bool = True) -> str:
    text = normalize_text_safe(text)
    text = split_alnum_boundaries(text)

    if use_placeholders:
        text = apply_placeholders_v2(text)

    text = clean_whitespace(text)
    return text

In [253]:
text = df["text"].iloc[19]
preprocess_sms(text, True)

0= England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/Ì¼1.20 POBOXox36504W45WQ 16+
1= England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/£1.20 POBOXox36504W45WQ 16+
2= England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4 txt/£1.20 POBOXox 36504 W 45 WQ 16+
3= England v Macedonia - dont miss the goals/team news. Txt ur national team to <NUM> eg ENGLAND to <NUM> Try:WALES, SCOTLAND <NUM> txt/<MONEY> POBOXox <NUM> W <NUM> WQ <NUM>+
4= England v Macedonia - dont miss the goals/team news. Txt ur national team to <NUM> eg ENGLAND to <NUM> Try:WALES, SCOTLAND <NUM> txt/<MONEY> POBOXox <NUM> W <NUM> WQ <NUM>+

'England v Macedonia - dont miss the goals/team news. Txt ur national team to <NUM> eg ENGLAND to <NUM> Try:WALES, SCOTLAND <NUM> txt/<MONEY> POBOXox <NUM> W <NUM> WQ <NUM>+'

In [254]:
s = df["text"].astype(str)

audit = {
    "rows": len(s),
    "pct_with_mojibake": (s.str.contains(MOJIBAKE_RE).mean() * 100),
    "pct_with_url": (s.str.contains(URL_RE).mean() * 100),
    "pct_with_money_symbol": (s.str.contains(r"[£$€]").mean() * 100),
    "pct_with_phone_like": (s.str.contains(PHONE_RE).mean() * 100),
}

df["text_clean"] = s.map(lambda x: preprocess_sms_v2(x, use_placeholders=False))
df["text_clean_ph"] = s.map(lambda x: preprocess_sms_v2(x, use_placeholders=True))

audit["pct_rows_changed_clean"] = ((df["text_clean"] != s).mean() * 100)
audit["pct_rows_changed_ph"] = ((df["text_clean_ph"] != s).mean() * 100)
audit

{'rows': 5572,
 'pct_with_mojibake': np.float64(4.666188083273511),
 'pct_with_url': np.float64(1.938262742282843),
 'pct_with_money_symbol': np.float64(4.953338119167265),
 'pct_with_phone_like': np.float64(7.483847810480976),
 'pct_rows_changed_clean': np.float64(99.96410624551328),
 'pct_rows_changed_ph': np.float64(99.96410624551328)}

In [255]:
df["text_clean"] = df["text"].map(preprocess_sms)

In [256]:
df.head(20)

                                                                                                                                                                                                       text target                                                                                                                                                                                            text_clean                                                                                                                                                                                         text_clean_ph
0                                                                                        Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...       ham                                                                                       Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...                                                                                       Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...
1                                                                                                                                                                          Ok lar... Joking wif u oni...       ham                                                                                                                                                                         Ok lar... Joking wif u oni...                                                                                                                                                                         Ok lar... Joking wif u oni...
2                                            Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's      spam                                 Free entry in <NUM> a wkly comp to win FA Cup final tkts <NUM> st May <NUM>. Text FA to <NUM> to receive entry question(std txt rate)T&C's apply <PHONE> over <NUM>'s                               Free entry in <NUM> a wkly comp to win FA Cup final tkts <NUM> st May <NUM> . Text FA to <NUM> to receive entry question(std txt rate)T&C's apply <PHONE> over <NUM> 's
3                                                                                                                                                      U dun say so early hor... U c already then say...       ham                                                                                                                                                     U dun say so early hor... U c already then say...                                                                                                                                                     U dun say so early hor... U c already then say...
4                                                                                                                                          Nah I don't think he goes to usf, he lives around here though       ham                                                                                                                                         Nah I don't think he goes to usf, he lives around here though                                                                                                                                         Nah I don't think he goes to usf, he lives around here though
5                                                   FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv      spam                                             FreeMsg Hey there darling it's been <NUM> week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, <MONEY> to rcv                                             FreeMsg Hey there darling it's been <NUM> week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, <MONEY> to rcv
6                                                                                                                          Even my brother is not like to speak with me. They treat me like aids patent.       ham                                                                                                                         Even my brother is not like to speak with me. They treat me like aids patent.                                                                                                                         Even my brother is not like to speak with me. They treat me like aids patent.
7                                       As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *9 to copy your friends Callertune       ham                                  As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press *<NUM> to copy your friends Callertune                                 As per your request 'Melle Melle (Oru Minnaminunginte Nurungu Vettam)' has been set as your callertune for all Callers. Press * <NUM> to copy your friends Callertune
8                                         WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.      spam                                    WINNER!! As a valued network customer you have been selected to receivea <MONEY> prize reward! To claim call <PHONE>. Claim code KL <NUM>. Valid <NUM> hours only.                                  WINNER!! As a valued network customer you have been selected to receivea <MONEY> prize reward! To claim call <PHONE> . Claim code KL <NUM> . Valid <NUM> hours only.
9                                             Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030      spam                                             Had your mobile <NUM> months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on <PHONE>                                             Had your mobile <NUM> months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on <PHONE>
10                                                                                         I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.       ham                                                                                         I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.                                                                                         I'm gonna be home soon and i don't want to talk about this stuff anymore tonight, k? I've cried enough today.
11                                                              SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info      spam                                          SIX chances to win CASH! From <NUM> to <NUM> pounds txt> CSH <NUM> and send to <NUM>. Cost <NUM> p/day, <NUM> days, <NUM>+ TsandCs apply Reply HL <NUM> info                                        SIX chances to win CASH! From <NUM> to <NUM> pounds txt> CSH <NUM> and send to <NUM> . Cost <NUM> p/day, <NUM> days, <NUM> + TsandCs apply Reply HL <NUM> info
12                                          URGENT! You have won a 1 week FREE membership in our å£100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18      spam                             URGENT! You have won a <NUM> week FREE membership in our <MONEY> Prize Jackpot! Txt the word: CLAIM to No: <NUM> T&C <URL> LCCLTD POBOX <NUM> LDNW <NUM> A <NUM> RW <NUM>                             URGENT! You have won a <NUM> week FREE membership in our <MONEY> Prize Jackpot! Txt the word: CLAIM to No: <NUM> T&C <URL> LCCLTD POBOX <NUM> LDNW <NUM> A <NUM> RW <NUM>
13  I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.       ham  I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.  I've been searching for the right words to thank you for this breather. I promise i wont take your help for granted and will fulfil my promise. You have been wonderful and a blessing at all times.
14                                                                                                                                                                   I HAVE A DATE ON SUNDAY WITH WILL!!       ham                                                                                                                                                                   I HAVE A DATE ON SUNDAY WITH WILL!!                                                                                                                                                                   I HAVE A DATE ON SUNDAY WITH WILL!!
15                                                 XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> http://wap. xxxmobilemovieclub.com?n=QJKGIGHJJGCBL      spam                                                       XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> <URL> xxxmobilemovieclub.com?n=QJKGIGHJJGCBL                                                       XXXMobileMovieClub: To use your credit, click the WAP link in the next txt message or click here>> <URL> xxxmobilemovieclub.com?n=QJKGIGHJJGCBL
16                                                                                                                                                                            Oh k...i'm watching here:)       ham                                                                                                                                                                            Oh k...i'm watching here:)                                                                                                                                                                            Oh k...i'm watching here:)
17                                                                                                                     Eh u remember how 2 spell his name... Yes i did. He v naughty make until i v wet.       ham                                                                                                                 Eh u remember how <NUM> spell his name... Yes i did. He v naughty make until i v wet.                                                                                                                 Eh u remember how <NUM> spell his name... Yes i did. He v naughty make until i v wet.
18                                                                                                                                            Fine if thatåÕs the way u feel. ThatåÕs the way its gota b       ham                                                                                                                                            Fine if thatåÕs the way u feel. ThatåÕs the way its gota b                                                                                                                                            Fine if thatåÕs the way u feel. ThatåÕs the way its gota b
19                                          England v Macedonia - dont miss the goals/team news. Txt ur national team to 87077 eg ENGLAND to 87077 Try:WALES, SCOTLAND 4txt/Ì¼1.20 POBOXox36504W45WQ 16+      spam                          England v Macedonia - dont miss the goals/team news. Txt ur national team to <NUM> eg ENGLAND to <NUM> Try:WALES, SCOTLAND <NUM> txt/<MONEY> POBOXox <NUM> W <NUM> WQ <NUM>+                        England v Macedonia - dont miss the goals/team news. Txt ur national team to <NUM> eg ENGLAND to <NUM> Try:WALES, SCOTLAND <NUM> txt/ <MONEY> POBOXox <NUM> W <NUM> WQ <NUM> +

In [257]:
# 1) exact duplicate text rows
dup_mask = df.duplicated(subset=["text"], keep=False)
dups = df.loc[dup_mask, ["text", "target"]].copy()

# 2) conflicting labels for same text
conflicts = (
    dups.groupby("text")["target"]
    .nunique()
    .reset_index(name="n_labels")
    .query("n_labels > 1")
)

print("duplicate rows:", dup_mask.sum())
print("conflicting-text groups:", len(conflicts))

duplicate rows: 684
conflicting-text groups: 0

In [258]:
conflict_texts = set(conflicts["text"])
df_model = df.loc[~df["text"].isin(conflict_texts)].copy()
df_model = df_model.drop_duplicates(subset=["text", "target"]).copy()

In [259]:
df_model.info()

<class 'pandas.DataFrame'>
Index: 5169 entries, 0 to 5571
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   text           5169 non-null   str
 1   target         5169 non-null   str
 2   text_clean     5169 non-null   str
 3   text_clean_ph  5169 non-null   str
dtypes: str(4)
memory usage: 201.9 KB

In [260]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

X = df_model["text_clean_ph"]   # or text / text_clean for ablation
y = df_model["target"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

vec = TfidfVectorizer(ngram_range=(1,2), min_df=2)
X_train_vec = vec.fit_transform(X_train)   # fit only on train
X_test_vec = vec.transform(X_test)         # transform test

## Ablation check (raw vs clean vs clean+placeholders)

In [261]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, f1_score, recall_score

variants = {
    "raw": "text",
    "clean": "text_clean",
    "clean_ph": "text_clean_ph",
}

results = []
for name, col in variants.items():
    X = df_model[col]
    y = df_model["target"]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    clf = Pipeline([
        ("tfidf", TfidfVectorizer(ngram_range=(1,2), min_df=2)),
        ("lr", LogisticRegression(max_iter=2000, class_weight="balanced"))
    ])

    clf.fit(X_train, y_train)
    pred = clf.predict(X_test)

    spam_recall = recall_score(y_test, pred, pos_label="spam")
    spam_f1 = f1_score(y_test, pred, pos_label="spam")
    weighted_f1 = f1_score(y_test, pred, average="weighted")

    results.append((name, spam_recall, spam_f1, weighted_f1))

results

[('raw', 0.9083969465648855, 0.9296875, 0.9824166961552256),
 ('clean', 0.9389312977099237, 0.924812030075188, 0.9807816038506586),
 ('clean_ph', 0.9389312977099237, 0.924812030075188, 0.9807816038506586)]

# Features

Ideas:
- percentage of uppercase to text length
- Placeholder counts (core signal): num_count, url_count, money_count, phone_count, plus binary flags like has_url, has_money.
- Message length features: character count, token count, average token length, placeholder ratio (placeholder_tokens / total_tokens).
- Spam-trigger token counts: count of words like free, win, claim, urgent, offer, prize, call, txt, stop.
- N-gram TF-IDF: word unigrams+bigrams and char 3–5 grams (char n-grams are very strong for noisy SMS text).
- Digit/alnum pattern intensity: number of mixed alnum tokens (x5, 4u), uppercase token count, punctuation burst count (!, ?, repeated symbols).
- Call-to-action patterns: presence of imperative phrases (call now, click, reply, text back), and short-code patterns.
- Lexical diversity: unique-token ratio and repeated-token ratio (spam often has repetitive wording).
- Position-aware placeholder features: whether url, money, or phone appears near message start/end.
- Rare token features: count of very low-frequency tokens (often promo codes, obfuscations).
- Classical metadata flags: starts with greeting, contains currency symbol, contains deadline language (today, now, last chance).